
MOVE_AHEAD = 'MoveAhead'
ROTATE_LEFT = 'RotateLeft'
ROTATE_RIGHT = 'RotateRight'
LOOK_UP = 'LookUp'
LOOK_DOWN = 'LookDown'
# DONE_TOMATO = 'DoneTomato'
# DONE_MICRO = 'DoneMicro'
# extra
OPEN_OBJECT = 'OpenObject'
CLOSE_OBJECT = 'CloseObject'
PICKUP_OBJECT = 'PickupObject'
PUT_OBJECT = 'PlaceHeldObject'
COOK = 'Cook'

BASIC_ACTIONS = [MOVE_AHEAD, ROTATE_LEFT, ROTATE_RIGHT, LOOK_UP, LOOK_DOWN]  # , DONE_BOWL]
ADVANCED_ACTIONS = BASIC_ACTIONS + [PICKUP_OBJECT, COOK]

GOAL_SUCCESS_REWARD = 5
SUCCESS_REWARD = GOAL_SUCCESS_REWARD / 2
STEP_PENALTY = -0.01
FAILED_ACTION_PENALTY = 0

