
MOVE_AHEAD = 'MoveAhead'
ROTATE_LEFT = 'RotateLeft'
ROTATE_RIGHT = 'RotateRight'
LOOK_UP = 'LookUp'
LOOK_DOWN = 'LookDown'
DONE1 = 'Done1'
DONE2 = 'Done2'
# extra
OPEN_OBJECT = 'OpenObject'
CLOSE_OBJECT = 'CloseObject'
PICKUP_OBJECT = 'PickupObject'
PUT_OBJECT = 'PutObject'

BASIC_ACTIONS = [MOVE_AHEAD, ROTATE_LEFT, ROTATE_RIGHT, LOOK_UP, LOOK_DOWN, DONE1, DONE2]
ADVANCED_ACTIONS = BASIC_ACTIONS + [OPEN_OBJECT, CLOSE_OBJECT, PICKUP_OBJECT, PUT_OBJECT]

GOAL_SUCCESS_REWARD = 5
STEP_PENALTY = -0.01
FAILED_ACTION_PENALTY = 0